'use strict';

/**
 * Manufacturer Return Authorization (RA) Service
 * Manages RAs sent to manufacturers for defective/warranty returns,
 * with communication logging, aging reports, and credit tracking.
 */

class ManufacturerRAService {
  constructor(pool, cache) {
    this.pool = pool;
    this.cache = cache;
  }

  // Valid status transitions
  static STATUS_TRANSITIONS = {
    pending_approval: ['approved', 'denied'],
    approved: ['shipped', 'denied'],
    shipped: ['received', 'closed'],
    received: ['credited', 'closed'],
    credited: ['closed'],
    closed: [],
    denied: []
  };

  /**
   * Create a new RA record. ra_number auto-generated by DB trigger.
   */
  async createRA(data) {
    const {
      manufacturer, manufacturer_ra_number, hub_return_id, warranty_claim_id,
      product_id, serial_number, reason, status, shipped_date,
      expected_credit_date, credit_amount, shipping_tracking_number,
      shipping_carrier, notes, created_by, tenant_id
    } = data;

    const result = await this.pool.query(`
      INSERT INTO manufacturer_ras (
        ra_number, manufacturer, manufacturer_ra_number, hub_return_id,
        warranty_claim_id, product_id, serial_number, reason, status,
        shipped_date, expected_credit_date, credit_amount,
        shipping_tracking_number, shipping_carrier, notes, created_by, tenant_id
      ) VALUES (
        '', $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
      ) RETURNING *
    `, [
      manufacturer, manufacturer_ra_number || null, hub_return_id || null,
      warranty_claim_id || null, product_id || null, serial_number || null,
      reason || 'defective', status || 'pending_approval',
      shipped_date || null, expected_credit_date || null, credit_amount || 0,
      shipping_tracking_number || null, shipping_carrier || null,
      notes || null, created_by, tenant_id || null
    ]);

    return result.rows[0];
  }

  /**
   * Get a single RA by ID with product info.
   */
  async getRA(id) {
    const result = await this.pool.query(`
      SELECT ra.*, p.name AS product_name, p.sku AS product_sku,
             u.first_name || ' ' || u.last_name AS created_by_name
      FROM manufacturer_ras ra
      LEFT JOIN products p ON ra.product_id = p.id
      LEFT JOIN users u ON ra.created_by = u.id
      WHERE ra.id = $1
    `, [id]);
    return result.rows[0] || null;
  }

  /**
   * Update RA status with transition validation.
   */
  async updateStatus(id, newStatus, data = {}) {
    const current = await this.getRA(id);
    if (!current) throw new Error('RA not found');

    const allowed = ManufacturerRAService.STATUS_TRANSITIONS[current.status] || [];
    if (!allowed.includes(newStatus)) {
      throw new Error(`Cannot transition from '${current.status}' to '${newStatus}'. Allowed: ${allowed.join(', ') || 'none'}`);
    }

    const updates = ['status = $1'];
    const values = [newStatus];
    let idx = 2;

    // Auto-set dates based on status
    if (newStatus === 'shipped' && !current.shipped_date) {
      updates.push(`shipped_date = $${idx++}`);
      values.push(data.shipped_date || new Date().toISOString().slice(0, 10));
    }
    if (newStatus === 'received' && !current.received_date) {
      updates.push(`received_date = $${idx++}`);
      values.push(data.received_date || new Date().toISOString().slice(0, 10));
    }
    if (newStatus === 'credited') {
      if (data.credit_amount !== undefined) { updates.push(`credit_amount = $${idx++}`); values.push(data.credit_amount); }
      if (data.credit_reference) { updates.push(`credit_reference = $${idx++}`); values.push(data.credit_reference); }
      updates.push(`credit_date = $${idx++}`);
      values.push(data.credit_date || new Date().toISOString().slice(0, 10));
    }

    // Optional fields
    if (data.manufacturer_ra_number !== undefined) { updates.push(`manufacturer_ra_number = $${idx++}`); values.push(data.manufacturer_ra_number); }
    if (data.shipping_tracking_number !== undefined) { updates.push(`shipping_tracking_number = $${idx++}`); values.push(data.shipping_tracking_number); }
    if (data.shipping_carrier !== undefined) { updates.push(`shipping_carrier = $${idx++}`); values.push(data.shipping_carrier); }
    if (data.expected_credit_date !== undefined) { updates.push(`expected_credit_date = $${idx++}`); values.push(data.expected_credit_date); }
    if (data.notes !== undefined) { updates.push(`notes = $${idx++}`); values.push(data.notes); }

    values.push(id);
    const result = await this.pool.query(
      `UPDATE manufacturer_ras SET ${updates.join(', ')} WHERE id = $${idx} RETURNING *`,
      values
    );

    return { before: current, after: result.rows[0] };
  }

  /**
   * Append a note to communication_log JSONB array.
   */
  async addCommunicationNote(id, userId, userName, note) {
    const entry = {
      date: new Date().toISOString(),
      user: userId,
      user_name: userName,
      note
    };

    const result = await this.pool.query(`
      UPDATE manufacturer_ras
      SET communication_log = communication_log || $1::jsonb
      WHERE id = $2
      RETURNING *
    `, [JSON.stringify(entry), id]);

    if (!result.rows.length) throw new Error('RA not found');
    return result.rows[0];
  }

  /**
   * List open RAs with aging, filtered.
   */
  async getOpenRAs(filters = {}) {
    const { manufacturer, status, overdue_only, limit = 100, offset = 0 } = filters;
    const conditions = [];
    const values = [];
    let idx = 1;

    if (manufacturer) { conditions.push(`ra.manufacturer ILIKE $${idx++}`); values.push(`%${manufacturer}%`); }
    if (status) { conditions.push(`ra.status = $${idx++}::ra_status`); values.push(status); }
    if (overdue_only) {
      conditions.push(`ra.shipped_date IS NOT NULL AND (CURRENT_DATE - ra.shipped_date) > 30`);
      conditions.push(`ra.status NOT IN ('closed', 'denied', 'credited')`);
    }

    const where = conditions.length ? 'WHERE ' + conditions.join(' AND ') : '';

    const result = await this.pool.query(`
      SELECT ra.*, p.name AS product_name, p.sku AS product_sku,
             u.first_name || ' ' || u.last_name AS created_by_name,
             CASE
               WHEN ra.shipped_date IS NOT NULL THEN (CURRENT_DATE - ra.shipped_date)
               ELSE (CURRENT_DATE - ra.created_at::date)
             END AS days_outstanding
      FROM manufacturer_ras ra
      LEFT JOIN products p ON ra.product_id = p.id
      LEFT JOIN users u ON ra.created_by = u.id
      ${where}
      ORDER BY ra.created_at DESC
      LIMIT $${idx++} OFFSET $${idx++}
    `, [...values, limit, offset]);

    const countResult = await this.pool.query(
      `SELECT COUNT(*) FROM manufacturer_ras ra ${where}`,
      values
    );

    return { rows: result.rows, total: parseInt(countResult.rows[0].count) };
  }

  /**
   * Group open RAs by manufacturer with totals.
   */
  async getRAsByManufacturer() {
    const result = await this.pool.query(`
      SELECT
        manufacturer,
        COUNT(*) AS total_ras,
        COUNT(*) FILTER (WHERE status NOT IN ('closed', 'denied', 'credited')) AS open_ras,
        COUNT(*) FILTER (WHERE shipped_date IS NOT NULL AND (CURRENT_DATE - shipped_date) > 30
                         AND status NOT IN ('closed', 'denied', 'credited')) AS overdue_ras,
        COALESCE(SUM(credit_amount) FILTER (WHERE status = 'credited'), 0) AS total_credited,
        COALESCE(SUM(credit_amount) FILTER (WHERE status NOT IN ('closed', 'denied', 'credited')), 0) AS expected_credit,
        MAX(CASE WHEN shipped_date IS NOT NULL AND status NOT IN ('closed', 'denied', 'credited')
                 THEN (CURRENT_DATE - shipped_date) ELSE 0 END) AS max_days_outstanding
      FROM manufacturer_ras
      GROUP BY manufacturer
      ORDER BY open_ras DESC, manufacturer
    `);
    return result.rows;
  }

  /**
   * Mark an RA as credited.
   */
  async markCredited(id, creditAmount, creditReference) {
    return this.updateStatus(id, 'credited', {
      credit_amount: creditAmount,
      credit_reference: creditReference
    });
  }

  /**
   * Aging report: all open RAs grouped by manufacturer.
   */
  async getAgingReport() {
    const summary = await this.getRAsByManufacturer();

    const detail = await this.pool.query(`
      SELECT * FROM v_manufacturer_ra_aging
      ORDER BY days_outstanding DESC
    `);

    return {
      summary,
      detail: detail.rows,
      generated_at: new Date().toISOString()
    };
  }
}

module.exports = ManufacturerRAService;
