/**
 * Sales Order Routes
 * API endpoints for Sales Order Confirmation — DB persistence, PDF generation,
 * and auto-invoice conversion for partial/account payments.
 */

const express = require('express');
const router = express.Router();
const { ApiError, asyncHandler } = require('../middleware/errorHandler');
const { authenticate } = require('../middleware/auth');

// ============================================================================
// MODULE STATE
// ============================================================================
let salesOrderService = null;
let posInvoiceService = null;
let pool = null;

// ============================================================================
// HELPERS
// ============================================================================

/**
 * Find or create a sales_orders record for a transaction.
 * Returns the sales order row.
 */
async function findOrCreateSalesOrder(transactionId, userId) {
  // Check if one already exists
  const existing = await pool.query(
    'SELECT * FROM sales_orders WHERE transaction_id = $1 LIMIT 1',
    [transactionId]
  );
  if (existing.rows.length) return existing.rows[0];

  // Fetch transaction totals + payments to compute balance
  const txnResult = await pool.query(
    'SELECT total_amount, customer_id, status FROM transactions WHERE transaction_id = $1',
    [transactionId]
  );
  if (!txnResult.rows.length) throw ApiError.notFound('Transaction');
  const txn = txnResult.rows[0];

  const paymentsResult = await pool.query(
    `SELECT COALESCE(SUM(amount), 0) AS total_paid
     FROM payments WHERE transaction_id = $1 AND status = 'completed'`,
    [transactionId]
  );
  const totalPaid = Math.round(parseFloat(paymentsResult.rows[0].total_paid) * 100); // to cents
  const totalAmount = Math.round(parseFloat(txn.total_amount) * 100);
  const balanceDue = Math.max(0, totalAmount - totalPaid);
  const status = balanceDue > 0 ? 'confirmed' : 'confirmed';

  // Insert — sales_order_number auto-generated by DB trigger
  const insertResult = await pool.query(`
    INSERT INTO sales_orders
      (sales_order_number, transaction_id, customer_id, status, total_amount, balance_due, created_by)
    VALUES
      ('', $1, $2, $3, $4, $5, $6)
    RETURNING *
  `, [transactionId, txn.customer_id, status, totalAmount, balanceDue, userId]);

  return insertResult.rows[0];
}

/**
 * If balance_due > 0, auto-generate an invoice and link it to the sales order.
 */
async function autoConvertToInvoice(salesOrder, transactionId) {
  if (salesOrder.balance_due <= 0) return salesOrder;
  if (salesOrder.status === 'invoiced') return salesOrder;

  try {
    // Generate invoice PDF (this persists the invoice data)
    await posInvoiceService.generateInvoicePdf(transactionId);

    // Update sales order status to invoiced
    const updated = await pool.query(`
      UPDATE sales_orders
      SET status = 'invoiced', updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [salesOrder.id]);

    return updated.rows[0] || salesOrder;
  } catch (err) {
    // Log but don't fail the sales order if invoice generation fails
    console.error('[SalesOrders] Auto-invoice conversion failed:', err.message);
    return salesOrder;
  }
}

// ============================================================================
// ROUTES
// ============================================================================

/**
 * POST /api/sales-orders/:id
 * Create a sales order record for a transaction (idempotent).
 * Auto-converts to invoice if balance_due > 0.
 */
router.post('/:id', authenticate, asyncHandler(async (req, res) => {
  const transactionId = parseInt(req.params.id, 10);
  if (isNaN(transactionId)) throw ApiError.badRequest('Invalid transaction ID');

  let salesOrder = await findOrCreateSalesOrder(transactionId, req.user?.id);

  // Auto-convert to invoice if balance remaining
  salesOrder = await autoConvertToInvoice(salesOrder, transactionId);

  res.success(salesOrder);
}));

/**
 * GET /api/sales-orders/:id/pdf
 * Download Sales Order Confirmation PDF.
 * Creates DB record if it doesn't exist yet.
 */
router.get('/:id/pdf', authenticate, asyncHandler(async (req, res) => {
  const transactionId = parseInt(req.params.id, 10);
  if (isNaN(transactionId)) throw ApiError.badRequest('Invalid transaction ID');

  // Ensure DB record exists
  let salesOrder = await findOrCreateSalesOrder(transactionId, req.user?.id);
  salesOrder = await autoConvertToInvoice(salesOrder, transactionId);

  const pdfBuffer = await salesOrderService.generateSalesOrderPdf(transactionId);

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="sales-order-${salesOrder.sales_order_number}.pdf"`);
  res.setHeader('Content-Length', pdfBuffer.length);
  res.send(pdfBuffer);
}));

/**
 * GET /api/sales-orders/:id/view
 * View Sales Order Confirmation PDF inline (browser preview).
 * Creates DB record if it doesn't exist yet.
 */
router.get('/:id/view', authenticate, asyncHandler(async (req, res) => {
  const transactionId = parseInt(req.params.id, 10);
  if (isNaN(transactionId)) throw ApiError.badRequest('Invalid transaction ID');

  let salesOrder = await findOrCreateSalesOrder(transactionId, req.user?.id);
  salesOrder = await autoConvertToInvoice(salesOrder, transactionId);

  const pdfBuffer = await salesOrderService.generateSalesOrderPdf(transactionId);

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="sales-order-${salesOrder.sales_order_number}.pdf"`);
  res.setHeader('Content-Length', pdfBuffer.length);
  res.send(pdfBuffer);
}));

/**
 * GET /api/sales-orders/:id/data
 * Get Sales Order data as JSON (includes DB record + PDF data).
 */
router.get('/:id/data', authenticate, asyncHandler(async (req, res) => {
  const transactionId = parseInt(req.params.id, 10);
  if (isNaN(transactionId)) throw ApiError.badRequest('Invalid transaction ID');

  const salesOrder = await findOrCreateSalesOrder(transactionId, req.user?.id);
  const data = await salesOrderService.getSalesOrderData(transactionId);

  res.success({
    ...data,
    salesOrder: {
      id: salesOrder.id,
      salesOrderNumber: salesOrder.sales_order_number,
      status: salesOrder.status,
      balanceDue: salesOrder.balance_due,
      invoiceId: salesOrder.invoice_id
    }
  });
}));

/**
 * GET /api/sales-orders/list/recent
 * List recent sales orders.
 */
router.get('/list/recent', authenticate, asyncHandler(async (req, res) => {
  const limit = Math.min(parseInt(req.query.limit) || 50, 200);
  const result = await pool.query(`
    SELECT so.*, t.transaction_number, c.name AS customer_name
    FROM sales_orders so
    LEFT JOIN transactions t ON so.transaction_id = t.transaction_id
    LEFT JOIN customers c ON so.customer_id = c.id
    ORDER BY so.created_at DESC
    LIMIT $1
  `, [limit]);

  res.success(result.rows);
}));

// ============================================================================
// INIT
// ============================================================================

const init = (deps) => {
  salesOrderService = deps.salesOrderService;
  posInvoiceService = deps.posInvoiceService;
  pool = deps.pool;
  return router;
};

module.exports = { init };
